### PR TITLE
new version

### PR DESCRIPTION
**Pull request by arsenovic**
This version does not include a LICENSE.txt yet, but the last version 0.14.4 does not exist on pypi. ( i made many errors because i am deployment noob)

### CODE REVIEW

**Comment by ocefpaf** [comment]
>  i made many errors because i am deployment noob

You would be surprised with the number of packages out there without the license listed in the metadata. It is not a noob mistake.

**Comment by arsenovic** [comment]
do i merge this?

**Comment by ocefpaf** [comment]
Yes, self merges are fair game in the feedstock.

**Comment by arsenovic** [comment]
so,  there is a scikit-rf recipe in  [anaconda](https://github.com/ContinuumIO/anaconda-recipes/tree/master/scikit-rf), by @ilanschnell.  is there a way to have that recipe point to this feedstock so that i can re-use all the infrastructure? or should a package be *either* in the official channel or in conda forge channel?

**Comment by arsenovic** [comment]
@ocefpaf  @ilanschnell ?

**Comment by ocefpaf** [comment]
@arsenovic there is no 'official' protocols to do that. It will depend on who is maintaining scikit-rf on defaults.

**Comment by arsenovic** [comment]
ok, thanks for your answer @ocefpaf .

on account of that, i  suggest we  remove scikit-rf from the default anaconda channel to avoid  redundancy. @ilanschnell is this ok?

**Pull request merged**
