### PR TITLE
version update

### PR DESCRIPTION
**Pull request by arsenovic**

### CODE REVIEW

**Comment by arsenovic** [comment]
@ocefpaf  do you have an idea why this error is caused?

https://ci.appveyor.com/project/conda-forge/scikit-rf-feedstock/build/1.0.10/job/gyjrtcg3ld8580rg

**Comment by ocefpaf** [comment]
> @ocefpaf do you have an idea why this error is caused?

It will be solved by the re-rendering you did above.

**Comment by arsenovic** [comment]
ok thanks, is there anyway to speed this up?

**Comment by ocefpaf** [comment]
Sorry, no. AppVeyor queue's is huge due to the updating bot.

**Comment by arsenovic** [comment]
@ocefpaf ,still failing appveyor. suggestions?

**Comment by ocefpaf** [comment]
The re-rendering commit did not work. Let's try again as a message here.

@conda-forge-admin, please rerender

**Comment by arsenovic** [comment]
you mean you want me to make a pr with "@conda-forge-admin, please rerender" in the comment?

**Comment by ocefpaf** [comment]
> you mean you want me to make a pr with "@conda-forge-admin, please rerender" in the comment?

You did that in https://github.com/conda-forge/scikit-rf-feedstock/pull/2/commits/e514333e2608a8586fe055258d542fdd8c0ed220 but https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender does not work with comments on the commit.

**Pull request merged**
